<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProviderTypesSeeder extends Seeder
{
    public function run()
    {
        $professions = [
            ['name' => 'Carpintero', 'need_control' => 0],
            ['name' => 'Abogado', 'need_control' => 1],
            ['name' => 'Doctor', 'need_control' => 1],
            ['name' => 'Cardiólogo', 'need_control' => 1],
            ['name' => 'Electricista', 'need_control' => 0],
            ['name' => 'Fontanero', 'need_control' => 0],
            ['name' => 'Mecánico', 'need_control' => 0],
            ['name' => 'Ingeniero Civil', 'need_control' => 1],
            ['name' => 'Arquitecto', 'need_control' => 1],
            ['name' => 'Psicólogo', 'need_control' => 1],
            ['name' => 'Pediatra', 'need_control' => 1],
            ['name' => 'Veterinario', 'need_control' => 1],
            ['name' => 'Dentista', 'need_control' => 1],
            ['name' => 'Contador', 'need_control' => 1],
            ['name' => 'Albañil', 'need_control' => 0],
            ['name' => 'Jardinero', 'need_control' => 0],
            ['name' => 'Chef', 'need_control' => 0],
            ['name' => 'Cocinero', 'need_control' => 0],
            ['name' => 'Cajero', 'need_control' => 0],
            ['name' => 'Panadero', 'need_control' => 0],
            ['name' => 'Pastelero', 'need_control' => 0],
            ['name' => 'Enfermero', 'need_control' => 1],
            ['name' => 'Partero', 'need_control' => 1],
            ['name' => 'Obstetra', 'need_control' => 1],
            ['name' => 'Ingeniero de Software', 'need_control' => 1],
            ['name' => 'Programador', 'need_control' => 0],
            ['name' => 'Diseñador Gráfico', 'need_control' => 0],
            ['name' => 'Fotógrafo', 'need_control' => 0],
            ['name' => 'Editor de Video', 'need_control' => 0],
            ['name' => 'Piloto', 'need_control' => 1],
            ['name' => 'Azafata', 'need_control' => 1],
            ['name' => 'Maestro', 'need_control' => 1],
            ['name' => 'Profesor Universitario', 'need_control' => 1],
            ['name' => 'Investigador', 'need_control' => 1],
            ['name' => 'Científico', 'need_control' => 1],
            ['name' => 'Físico', 'need_control' => 1],
            ['name' => 'Químico', 'need_control' => 1],
            ['name' => 'Biólogo', 'need_control' => 1],
            ['name' => 'Farmacéutico', 'need_control' => 1],
            ['name' => 'Técnico en Computación', 'need_control' => 0],
            ['name' => 'Técnico en Redes', 'need_control' => 0],
            ['name' => 'Soldador', 'need_control' => 0],
            ['name' => 'Pintor de Casas', 'need_control' => 0],
            ['name' => 'Pintor Automotriz', 'need_control' => 0],
            ['name' => 'Tapicero', 'need_control' => 0],
            ['name' => 'Chofer de Taxi', 'need_control' => 0],
            ['name' => 'Chofer de Camión', 'need_control' => 0],
            ['name' => 'Guardia de Seguridad', 'need_control' => 0],
            ['name' => 'Agente de Seguros', 'need_control' => 1],
            ['name' => 'Analista Financiero', 'need_control' => 1],
            ['name' => 'Administrador', 'need_control' => 1],
            ['name' => 'Recepcionista', 'need_control' => 0],
            ['name' => 'Secretaria', 'need_control' => 0],
            ['name' => 'Auxiliar Administrativo', 'need_control' => 0],
            ['name' => 'Barbero', 'need_control' => 0],
            ['name' => 'Estilista', 'need_control' => 0],
            ['name' => 'Manicurista', 'need_control' => 0],
            ['name' => 'Pedicurista', 'need_control' => 0],
            ['name' => 'Esteticista', 'need_control' => 0],
            ['name' => 'Maquillista', 'need_control' => 0],
            ['name' => 'Tatuador', 'need_control' => 0],
            ['name' => 'Perforador Corporal', 'need_control' => 0],
            ['name' => 'Músico', 'need_control' => 0],
            ['name' => 'Cantante', 'need_control' => 0],
            ['name' => 'Actor', 'need_control' => 0],
            ['name' => 'Bailarín', 'need_control' => 0],
            ['name' => 'Escultor', 'need_control' => 0],
            ['name' => 'Pintor Artístico', 'need_control' => 0],
            ['name' => 'Escritor', 'need_control' => 0],
            ['name' => 'Periodista', 'need_control' => 1],
            ['name' => 'Fotoperiodista', 'need_control' => 1],
            ['name' => 'Director de Cine', 'need_control' => 0],
            ['name' => 'Guionista', 'need_control' => 0],
            ['name' => 'Productor', 'need_control' => 0],
            ['name' => 'Director de Teatro', 'need_control' => 0],
            ['name' => 'Camarógrafo', 'need_control' => 0],
            ['name' => 'Técnico de Sonido', 'need_control' => 0],
            ['name' => 'Locutor', 'need_control' => 0],
            ['name' => 'Animador', 'need_control' => 0],
            ['name' => 'Editor de Música', 'need_control' => 0],
            ['name' => 'Productor Musical', 'need_control' => 0],
            ['name' => 'DJ', 'need_control' => 0],
            ['name' => 'Reparador de Electrodomésticos', 'need_control' => 0],
            ['name' => 'Técnico en Refrigeración', 'need_control' => 0],
            ['name' => 'Técnico en Aire Acondicionado', 'need_control' => 0],
            ['name' => 'Reparador de Bicicletas', 'need_control' => 0],
            ['name' => 'Reparador de Motocicletas', 'need_control' => 0],
            ['name' => 'Reparador de Relojes', 'need_control' => 0],
            ['name' => 'Reparador de Calzado', 'need_control' => 0],
            ['name' => 'Sastre', 'need_control' => 0],
            ['name' => 'Modista', 'need_control' => 0],
            ['name' => 'Diseñador de Moda', 'need_control' => 1],
            ['name' => 'Ortopedista', 'need_control' => 1],
            ['name' => 'Dermatólogo', 'need_control' => 1],
            ['name' => 'Neurólogo', 'need_control' => 1],
            ['name' => 'Psiquiatra', 'need_control' => 1],
            ['name' => 'Urólogo', 'need_control' => 1],
            ['name' => 'Oncólogo', 'need_control' => 1],
            ['name' => 'Gastroenterólogo', 'need_control' => 1],
            ['name' => 'Nutriólogo', 'need_control' => 1],
            ['name' => 'Endocrinólogo', 'need_control' => 1],
            ['name' => 'Neumólogo', 'need_control' => 1],
            ['name' => 'Ginecólogo', 'need_control' => 1],
            ['name' => 'Traumatólogo', 'need_control' => 1],
            ['name' => 'Anestesiólogo', 'need_control' => 1],
            ['name' => 'Radiólogo', 'need_control' => 1],
            ['name' => 'Cirujano General', 'need_control' => 1],
            ['name' => 'Cirujano Plástico', 'need_control' => 1],
            ['name' => 'Oftalmólogo', 'need_control' => 1],
            ['name' => 'Otorrinolaringólogo', 'need_control' => 1],
            ['name' => 'Odontopediatra', 'need_control' => 1],
            ['name' => 'Fisioterapeuta', 'need_control' => 1],
            ['name' => 'Reumatólogo', 'need_control' => 1],
            ['name' => 'Hematólogo', 'need_control' => 1],
            ['name' => 'Patólogo', 'need_control' => 1],
            ['name' => 'Neonatólogo', 'need_control' => 1],
            ['name' => 'Alergólogo', 'need_control' => 1],
            ['name' => 'Inmunólogo', 'need_control' => 1],
            ['name' => 'Cirujano Cardiovascular', 'need_control' => 1],
            ['name' => 'Proctólogo', 'need_control' => 1],
            ['name' => 'Cirujano de Mano', 'need_control' => 1],
            ['name' => 'Cirujano Oncológico', 'need_control' => 1],
            ['name' => 'Cirujano Pediátrico', 'need_control' => 1],
            ['name' => 'Cirujano Torácico', 'need_control' => 1],
            ['name' => 'Cirujano Vascular', 'need_control' => 1],
            ['name' => 'Ingeniero Mecánico', 'need_control' => 1],
            ['name' => 'Ingeniero Eléctrico', 'need_control' => 1],
            ['name' => 'Ingeniero Electrónico', 'need_control' => 1],
            ['name' => 'Ingeniero Industrial', 'need_control' => 1],
            ['name' => 'Ingeniero en Sistemas', 'need_control' => 1],
            ['name' => 'Ingeniero en Telecomunicaciones', 'need_control' => 1],
            ['name' => 'Ingeniero Químico', 'need_control' => 1],
            ['name' => 'Ingeniero Petrolero', 'need_control' => 1],
            ['name' => 'Ingeniero Metalúrgico', 'need_control' => 1],
            ['name' => 'Ingeniero Agrónomo', 'need_control' => 1],
            ['name' => 'Ingeniero Forestal', 'need_control' => 1],
            ['name' => 'Agricultor', 'need_control' => 0],
            ['name' => 'Ganadero', 'need_control' => 0],
            ['name' => 'Apicultor', 'need_control' => 0],
            ['name' => 'Pescador', 'need_control' => 0],
            ['name' => 'Marino', 'need_control' => 1],
            ['name' => 'Comerciante', 'need_control' => 0],
            ['name' => 'Empresario', 'need_control' => 0],
            ['name' => 'Emprendedor', 'need_control' => 0],
            ['name' => 'Gerente', 'need_control' => 1],
            ['name' => 'Director de Empresa', 'need_control' => 1],
            ['name' => 'Consultor', 'need_control' => 0],
            ['name' => 'Asesor Financiero', 'need_control' => 1],
            ['name' => 'Asesor de Imagen', 'need_control' => 0],
            ['name' => 'Asesor de Ventas', 'need_control' => 0],
            ['name' => 'Asesor Jurídico', 'need_control' => 1],
            ['name' => 'Asistente de Dirección', 'need_control' => 0],
            ['name' => 'Asistente Ejecutivo', 'need_control' => 0],
            ['name' => 'Analista de Sistemas', 'need_control' => 1],
            ['name' => 'Analista de Datos', 'need_control' => 1],
            ['name' => 'Analista de Marketing', 'need_control' => 1],
            ['name' => 'Agente de Bienes Raíces', 'need_control' => 1],
            ['name' => 'Corredor de Bolsa', 'need_control' => 1],
            ['name' => 'Abogado Corporativo', 'need_control' => 1],
            ['name' => 'Abogado Penalista', 'need_control' => 1],
            ['name' => 'Juez', 'need_control' => 1],
            ['name' => 'Notario', 'need_control' => 1],
            ['name' => 'Mediador', 'need_control' => 1],
            ['name' => 'Procurador', 'need_control' => 1],
            ['name' => 'Diplomático', 'need_control' => 1],
            ['name' => 'Cónsul', 'need_control' => 1],
            ['name' => 'Embajador', 'need_control' => 1],
            ['name' => 'Funcionario Público', 'need_control' => 0],
            ['name' => 'Político', 'need_control' => 0],
            ['name' => 'Senador', 'need_control' => 1],
            ['name' => 'Diputado', 'need_control' => 1],
            ['name' => 'Alcalde', 'need_control' => 1],
            ['name' => 'Gobernador', 'need_control' => 1],
            ['name' => 'Presidente', 'need_control' => 1],
            ['name' => 'Asesor Político', 'need_control' => 0],
            ['name' => 'Consultor Político', 'need_control' => 0],
            ['name' => 'Analista Político', 'need_control' => 0],
            ['name' => 'Experto en Seguridad', 'need_control' => 1],
            ['name' => 'Experto en Ciberseguridad', 'need_control' => 1],
            ['name' => 'Consultor en Recursos Humanos', 'need_control' => 1],
            ['name' => 'Especialista en Talento Humano', 'need_control' => 1],
            ['name' => 'Gerente de Recursos Humanos', 'need_control' => 1],
            ['name' => 'Director de Recursos Humanos', 'need_control' => 1],
            ['name' => 'Reclutador', 'need_control' => 0],
            ['name' => 'Entrenador Personal', 'need_control' => 0],
            ['name' => 'Instructor de Yoga', 'need_control' => 0],
            ['name' => 'Instructor de Pilates', 'need_control' => 0],
            ['name' => 'Instructor de Zumba', 'need_control' => 0],
            ['name' => 'Instructor de Artes Marciales', 'need_control' => 0],
            ['name' => 'Maestro de Ceremonias', 'need_control' => 0],
            ['name' => 'Maestro de Cocina', 'need_control' => 0],
            ['name' => 'Maestro de Música', 'need_control' => 0],
            ['name' => 'Instructor de Buceo', 'need_control' => 1],
            ['name' => 'Guía Turístico', 'need_control' => 0],
            ['name' => 'Guía de Montaña', 'need_control' => 1],
            ['name' => 'Guía de Safari', 'need_control' => 1],
            ['name' => 'Piloto de Drones', 'need_control' => 1],
            ['name' => 'Fotógrafo Aéreo', 'need_control' => 0],
            ['name' => 'Bombero', 'need_control' => 1],
            ['name' => 'Paramédico', 'need_control' => 1],
            ['name' => 'Rescatista', 'need_control' => 1],
            ['name' => 'Socorrista', 'need_control' => 1],
            ['name' => 'Policía', 'need_control' => 1],
            ['name' => 'Detective Privado', 'need_control' => 1],
            ['name' => 'Investigador Forense', 'need_control' => 1],
            ['name' => 'Perito', 'need_control' => 1],
            ['name' => 'Agente Aduanal', 'need_control' => 1],
            ['name' => 'Despachante de Aduanas', 'need_control' => 1],
            ['name' => 'Especialista en Logística', 'need_control' => 1],
            ['name' => 'Especialista en Comercio Exterior', 'need_control' => 1],
            ['name' => 'Gerente de Operaciones', 'need_control' => 1],
            ['name' => 'Gerente de Producción', 'need_control' => 1],
            ['name' => 'Supervisor de Planta', 'need_control' => 1],
            ['name' => 'Supervisor de Calidad', 'need_control' => 1],
            ['name' => 'Inspector de Calidad', 'need_control' => 1],
            ['name' => 'Especialista en Control de Calidad', 'need_control' => 1],
            ['name' => 'Especialista en Medio Ambiente', 'need_control' => 1],
            ['name' => 'Consultor Ambiental', 'need_control' => 1],
            ['name' => 'Ingeniero Ambiental', 'need_control' => 1],
            ['name' => 'Gerente de Marketing', 'need_control' => 1],
            ['name' => 'Director de Marketing', 'need_control' => 1],
            ['name' => 'Especialista en Marketing Digital', 'need_control' => 1],
            ['name' => 'Community Manager', 'need_control' => 0],
            ['name' => 'Gestor de Redes Sociales', 'need_control' => 0],
            ['name' => 'Especialista en SEO', 'need_control' => 1],
            ['name' => 'Especialista en SEM', 'need_control' => 1],
            ['name' => 'Analista de Datos de Marketing', 'need_control' => 1],
            ['name' => 'Gerente de Producto', 'need_control' => 1],
            ['name' => 'Brand Manager', 'need_control' => 1],
            ['name' => 'Especialista en Publicidad', 'need_control' => 1],
            ['name' => 'Ejecutivo de Cuentas', 'need_control' => 0],
            ['name' => 'Planificador de Medios', 'need_control' => 1],
            ['name' => 'Asesor de Imagen Corporativa', 'need_control' => 1],
            ['name' => 'Consultor de Negocios', 'need_control' => 1],
            ['name' => 'Consultor de Estrategia', 'need_control' => 1],
            ['name' => 'Consultor de Innovación', 'need_control' => 1],
            ['name' => 'Consultor de Desarrollo Sostenible', 'need_control' => 1],
            ['name' => 'Asesor de RSE', 'need_control' => 1],
            ['name' => 'Consultor de Cambio Climático', 'need_control' => 1],
            ['name' => 'Consultor de Energías Renovables', 'need_control' => 1],
            ['name' => 'Consultor de Eficiencia Energética', 'need_control' => 1],
            ['name' => 'Especialista en Finanzas Sostenibles', 'need_control' => 1],
            ['name' => 'Gerente de Proyectos', 'need_control' => 1],
            ['name' => 'Director de Proyectos', 'need_control' => 1],
            ['name' => 'Especialista en Gestión de Proyectos', 'need_control' => 1],
            ['name' => 'Consultor de Transformación Digital', 'need_control' => 1],
            ['name' => 'Consultor de Gestión del Cambio', 'need_control' => 1],
            ['name' => 'Especialista en Procesos', 'need_control' => 1],
            ['name' => 'Especialista en Mejora Continua', 'need_control' => 1],
            ['name' => 'Gerente de Innovación', 'need_control' => 1],
            ['name' => 'Director de Innovación', 'need_control' => 1],
            ['name' => 'Consultor de Calidad', 'need_control' => 1],
            ['name' => 'Consultor de Riesgos', 'need_control' => 1],
            ['name' => 'Consultor de Cumplimiento Normativo', 'need_control' => 1],
            ['name' => 'Consultor de Seguridad Industrial', 'need_control' => 1],
            ['name' => 'Especialista en Seguridad Alimentaria', 'need_control' => 1],
            ['name' => 'Especialista en Seguridad Química', 'need_control' => 1],
            ['name' => 'Especialista en Seguridad en la Construcción', 'need_control' => 1],
            ['name' => 'Consultor en Ergonomía', 'need_control' => 1],
            ['name' => 'Especialista en Higiene Industrial', 'need_control' => 1],
            ['name' => 'Gerente de Salud y Seguridad', 'need_control' => 1],
            ['name' => 'Director de Salud y Seguridad', 'need_control' => 1],
            ['name' => 'Consultor de Seguridad Física', 'need_control' => 1],
            ['name' => 'Especialista en Seguridad Vial', 'need_control' => 1],
            ['name' => 'Especialista en Transporte y Logística', 'need_control' => 1],
            ['name' => 'Consultor en Movilidad Urbana', 'need_control' => 1],
            ['name' => 'Especialista en Movilidad Sostenible', 'need_control' => 1],
            ['name' => 'Consultor en Políticas Públicas', 'need_control' => 1],
            ['name' => 'Consultor en Relaciones Internacionales', 'need_control' => 1],
            ['name' => 'Analista de Inteligencia', 'need_control' => 1],
            ['name' => 'Especialista en Desarrollo de Software', 'need_control' => 1],
            ['name' => 'Especialista en Automatización de Procesos', 'need_control' => 1],
            ['name' => 'Especialista en Ciencia de Datos', 'need_control' => 1],
            ['name' => 'Consultor de Big Data', 'need_control' => 1],
            ['name' => 'Especialista en Inteligencia Artificial', 'need_control' => 1],
            ['name' => 'Consultor de Machine Learning', 'need_control' => 1],
            ['name' => 'Especialista en Blockchain', 'need_control' => 1],
            ['name' => 'Consultor de Ciberseguridad', 'need_control' => 1],
            ['name' => 'Especialista en Criptomonedas', 'need_control' => 1],
            ['name' => 'Consultor de Fintech', 'need_control' => 1],
            ['name' => 'Especialista en Pago Digital', 'need_control' => 1],
            ['name' => 'Consultor en Tecnologías Emergentes', 'need_control' => 1],
            ['name' => 'Especialista en Internet de las Cosas (IoT)', 'need_control' => 1],
            ['name' => 'Especialista en Realidad Aumentada', 'need_control' => 1],
            ['name' => 'Especialista en Realidad Virtual', 'need_control' => 1],
            ['name' => 'Consultor de Transformación Organizacional', 'need_control' => 1],
            ['name' => 'Consultor en Gestión del Talento', 'need_control' => 1],
            ['name' => 'Especialista en Gestión del Conocimiento', 'need_control' => 1],
            ['name' => 'Especialista en Aprendizaje Organizacional', 'need_control' => 1],
            ['name' => 'Consultor en Desarrollo Organizacional', 'need_control' => 1],
            ['name' => 'Especialista en Comunicación Interna', 'need_control' => 1],
            ['name' => 'Consultor en Cultura Corporativa', 'need_control' => 1],
            ['name' => 'Consultor en Bienestar Corporativo', 'need_control' => 1],
            ['name' => 'Especialista en Inclusión y Diversidad', 'need_control' => 1],
            ['name' => 'Consultor en Responsabilidad Social Empresarial', 'need_control' => 1],
            ['name' => 'Consultor en Gobernanza Corporativa', 'need_control' => 1],
            ['name' => 'Especialista en Liderazgo', 'need_control' => 1],
            ['name' => 'Especialista en Desarrollo de Talento', 'need_control' => 1],
            ['name' => 'Coach Ejecutivo', 'need_control' => 1],
            ['name' => 'Consultor en Estrategia de Innovación', 'need_control' => 1],
            ['name' => 'Consultor en Desarrollo de Productos', 'need_control' => 1],
            ['name' => 'Especialista en Innovación Abierta', 'need_control' => 1],
            ['name' => 'Especialista en Desarrollo de Ecosistemas de Innovación', 'need_control' => 1],
            ['name' => 'Consultor en Diseño de Servicios', 'need_control' => 1],
            ['name' => 'Consultor en Diseño de Experiencia de Usuario', 'need_control' => 1],
            ['name' => 'Especialista en Diseño Centrado en el Usuario', 'need_control' => 1],
            ['name' => 'Consultor en Experiencia del Cliente', 'need_control' => 1],
            ['name' => 'Consultor en Inteligencia de Negocios', 'need_control' => 1],
            ['name' => 'Especialista en Business Intelligence', 'need_control' => 1],
            ['name' => 'Consultor en Data Science', 'need_control' => 1],
            ['name' => 'Consultor en Data Analytics', 'need_control' => 1],
            ['name' => 'Especialista en Data Mining', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de Proyectos Tecnológicos', 'need_control' => 1],
            ['name' => 'Especialista en Gestión de la Innovación Tecnológica', 'need_control' => 1],
            ['name' => 'Consultor en Gestión del Cambio Digital', 'need_control' => 1],
            ['name' => 'Especialista en Desarrollo de Software Ágil', 'need_control' => 1],
            ['name' => 'Consultor en Metodologías Ágiles', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de Riesgos Tecnológicos', 'need_control' => 1],
            ['name' => 'Especialista en Gobierno de TI', 'need_control' => 1],
            ['name' => 'Consultor en Arquitectura Empresarial', 'need_control' => 1],
            ['name' => 'Especialista en Infraestructura TI', 'need_control' => 1],
            ['name' => 'Consultor en Soluciones Cloud', 'need_control' => 1],
            ['name' => 'Especialista en Migración a la Nube', 'need_control' => 1],
            ['name' => 'Consultor en Continuidad del Negocio', 'need_control' => 1],
            ['name' => 'Especialista en Recuperación ante Desastres', 'need_control' => 1],
            ['name' => 'Consultor en Seguridad de la Información', 'need_control' => 1],
            ['name' => 'Especialista en Privacidad de Datos', 'need_control' => 1],
            ['name' => 'Consultor en Cumplimiento de TI', 'need_control' => 1],
            ['name' => 'Especialista en Auditoría de TI', 'need_control' => 1],
            ['name' => 'Consultor en Riesgos de Ciberseguridad', 'need_control' => 1],
            ['name' => 'Especialista en Respuesta a Incidentes de Seguridad', 'need_control' => 1],
            ['name' => 'Consultor en Protección de Infraestructura Crítica', 'need_control' => 1],
            ['name' => 'Especialista en Seguridad en la Nube', 'need_control' => 1],
            ['name' => 'Consultor en Arquitectura de Ciberseguridad', 'need_control' => 1],
            ['name' => 'Especialista en Gestión de Identidades y Accesos', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de Vulnerabilidades', 'need_control' => 1],
            ['name' => 'Especialista en Gestión de Parches', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de Logística y Cadena de Suministro', 'need_control' => 1],
            ['name' => 'Especialista en Optimización de la Cadena de Suministro', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de la Demanda', 'need_control' => 1],
            ['name' => 'Especialista en Gestión de Inventarios', 'need_control' => 1],
            ['name' => 'Consultor en Mejora de Procesos Logísticos', 'need_control' => 1],
            ['name' => 'Especialista en Comercio Electrónico', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de Proyectos de eCommerce', 'need_control' => 1],
            ['name' => 'Especialista en Estrategia de eCommerce', 'need_control' => 1],
            ['name' => 'Consultor en Marketing Digital para eCommerce', 'need_control' => 1],
            ['name' => 'Especialista en Logística de eCommerce', 'need_control' => 1],
            ['name' => 'Consultor en Experiencia del Cliente para eCommerce', 'need_control' => 1],
            ['name' => 'Especialista en Integración de Sistemas para eCommerce', 'need_control' => 1],
            ['name' => 'Consultor en Plataformas de eCommerce', 'need_control' => 1],
            ['name' => 'Especialista en Ventas Online', 'need_control' => 1],
            ['name' => 'Consultor en Estrategia Omnicanal', 'need_control' => 1],
            ['name' => 'Especialista en Fidelización de Clientes', 'need_control' => 1],
            ['name' => 'Consultor en Programas de Lealtad', 'need_control' => 1],
            ['name' => 'Especialista en Customer Relationship Management (CRM)', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de la Relación con el Cliente', 'need_control' => 1],
            ['name' => 'Especialista en Comunicación Multicanal', 'need_control' => 1],
            ['name' => 'Consultor en Innovación en el Punto de Venta', 'need_control' => 1],
            ['name' => 'Especialista en Diseño de Espacios Comerciales', 'need_control' => 1],
            ['name' => 'Consultor en Marketing Sensorial', 'need_control' => 1],
            ['name' => 'Especialista en Estrategia de Precios', 'need_control' => 1],
            ['name' => 'Consultor en Pricing', 'need_control' => 1],
            ['name' => 'Especialista en Revenue Management', 'need_control' => 1],
            ['name' => 'Consultor en Yield Management', 'need_control' => 1],
            ['name' => 'Especialista en Gestión de la Oferta y la Demanda', 'need_control' => 1],
            ['name' => 'Consultor en Desarrollo de Canales de Distribución', 'need_control' => 1],
            ['name' => 'Especialista en Gestión de la Distribución', 'need_control' => 1],
            ['name' => 'Consultor en Innovación en la Cadena de Valor', 'need_control' => 1],
            ['name' => 'Especialista en Estrategia de Crecimiento', 'need_control' => 1],
            ['name' => 'Consultor en Fusiones y Adquisiciones', 'need_control' => 1],
            ['name' => 'Especialista en Integración Post-Fusión', 'need_control' => 1],
            ['name' => 'Consultor en Estrategia de Expansión Internacional', 'need_control' => 1],
            ['name' => 'Especialista en Desarrollo de Nuevos Negocios', 'need_control' => 1],
            ['name' => 'Consultor en Gestión del Cambio Organizacional', 'need_control' => 1],
            ['name' => 'Especialista en Planificación Estratégica', 'need_control' => 1],
            ['name' => 'Consultor en Estrategia Corporativa', 'need_control' => 1],
            ['name' => 'Especialista en Análisis Competitivo', 'need_control' => 1],
            ['name' => 'Consultor en Desarrollo Organizacional', 'need_control' => 1],
            ['name' => 'Especialista en Cultura Organizacional', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de la Innovación Empresarial', 'need_control' => 1],
            ['name' => 'Especialista en Innovación Abierta', 'need_control' => 1],
            ['name' => 'Consultor en Desarrollo de Productos', 'need_control' => 1],
            ['name' => 'Especialista en Gestión de Proyectos de Innovación', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de la Innovación Digital', 'need_control' => 1],
            ['name' => 'Especialista en Transformación Digital', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de la Innovación Disruptiva', 'need_control' => 1],
            ['name' => 'Especialista en Estrategia de Innovación', 'need_control' => 1],
            ['name' => 'Consultor en Desarrollo de Nuevas Tecnologías', 'need_control' => 1],
            ['name' => 'Especialista en Tecnología e Innovación', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de la Innovación Tecnológica', 'need_control' => 1],
            ['name' => 'Especialista en Innovación en Modelos de Negocio', 'need_control' => 1],
            ['name' => 'Consultor en Estrategia de Crecimiento y Escalabilidad', 'need_control' => 1],
            ['name' => 'Especialista en Expansión de Negocios', 'need_control' => 1],
            ['name' => 'Consultor en Innovación Abierta', 'need_control' => 1],
            ['name' => 'Especialista en Gestión de Proyectos Tecnológicos', 'need_control' => 1],
            ['name' => 'Consultor en Transformación Organizacional', 'need_control' => 1],
            ['name' => 'Especialista en Gestión del Talento', 'need_control' => 1],
            ['name' => 'Consultor en Desarrollo de Talento', 'need_control' => 1],
            ['name' => 'Especialista en Estrategia de Crecimiento Empresarial', 'need_control' => 1],
            ['name' => 'Consultor en Estrategia de Innovación Empresarial', 'need_control' => 1],
            ['name' => 'Especialista en Desarrollo de Nuevas Tecnologías', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de la Innovación Disruptiva', 'need_control' => 1],
            ['name' => 'Especialista en Estrategia de Innovación Tecnológica', 'need_control' => 1],
            ['name' => 'Consultor en Innovación en Modelos de Negocio', 'need_control' => 1],
            ['name' => 'Especialista en Estrategia de Crecimiento y Escalabilidad', 'need_control' => 1],
            ['name' => 'Consultor en Gestión de la Innovación Empresarial', 'need_control' => 1],
        ];
        

        foreach ($professions as $profession) {
            DB::table('provider_types')->insert([
                'name' => $profession['name'],
                'need_control' => $profession['need_control'],
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
